export const TUNISIA_LOCATIONS: Record<string, string[]> = {
  "Ariana": ["Ariana Ville", "La Soukra", "Raoued", "Mnihla", "Kalâat el-Andalous", "Sidi Thabet"],
  "Beja": ["Béja Nord", "Nefza", "Medjez el-Bab", "Béja Sud", "Testour", "Téboursouk", "Amdoun", "Goubellat", "Thibar"],
  "Ben Arous": ["El Mourouj", "Fouchana", "Mornag", "Mohamedia", "Radès", "Medina Jedida", "Hammam Lif", "Ben Arous", "Ezzahra", "Bou Mhel el-Bassatine", "Hammam Chott", "Mégrine"],
  "Bizerte": ["Bizerte Nord", "Menzel Bourguiba", "Ras Jebel", "Mateur", "Bizerte Sud", "Sejnane", "Menzel Jemil", "Joumine", "Ghezala", "El Alia", "Zarzouna", "Tinja", "Ghar El Melh", "Utique"],
  "Gabès": ["El Hamma", "Gabès Sud", "Mareth", "Gabès Médina", "Gabès Ouest", "Métouia", "Ghannouch", "Nouvelle Matmata", "Menzel El Habib", "Matmata"],
  "Gafsa": ["Gafsa Sud", "Métlaoui", "Sened", "El Ksar", "Moularès", "Redeyef", "El Guettar", "Belkhir", "Mdhilla", "Gafsa Nord", "Sidi Aïch"],
  "Jendouba": ["Jendouba Sud", "Jendouba", "Ghardimaou", "Fernana", "Tabarka", "Jendouba Nord", "Balta-Bou Aouane", "Aïn Draham", "Bou Salem", "Oued Meliz"],
  "Kairouan": ["Kairouan Nord", "Kairouan Sud", "Bou Hajla", "Sbikha", "Haffouz", "Nasrallah", "Oueslatia", "Hajeb El Ayoun", "Chebika", "El Alâa", "Echrarda"],
  "Kasserine": ["Sbeïtla", "Kasserine Nord", "Fériana", "Sbiba", "Foussana", "Thala", "Majel Bel Abbès", "Kasserine Sud", "Ezzouhour", "El Ayoun", "Hassi El Ferid", "Jedelienne", "Haïdra"],
  "Kebili": ["Kébili Sud", "Kébili Nord", "Souk Lahad", "Douz Nord", "Douz Sud", "Faouar"],
  "Kef": ["Kef Est", "Kef Ouest", "Dahmani", "Tajerouine", "Nebeur", "Sers", "Sakiet Sidi Youssef", "El Ksour", "Kalaat Senan", "Jérissa", "Kalâat Khasba"],
  "Mahdia": ["Mahdia", "Ksour Essef", "Essouassi", "El Jem", "Sidi Alouane", "Bou Merdes", "Chorbane", "Chebba", "Hebira", "Melloulèche", "Ouled Chamekh", "Rejiche", "El Bradâa"],
  "Manouba": ["Ettadhamen", "Douar Hicher", "Oued Ellil", "La Manouba", "Tebourba", "Djedeida", "Mornaguia", "El Batan", "Borj El Amri"],
  "Medenine": ["Zarzis", "Ben Gardane", "Djerba - Houmt Souk", "Djerba - Midoun", "Médenine Nord", "Médenine Sud", "Beni Khedache", "Djerba - Ajim", "Sidi Makhlouf"],
  "Monastir": ["Monastir", "Moknine", "Jemmal", "Ksar Hellal", "Téboulba", "Ksibet el-Médiouni", "Bembla", "Zéramdine", "Sayada-Lamta-Bou Hajar", "Sahline", "Ouerdanine", "Bekalta", "Beni Hassen"],
  "Nabeul": ["Hammamet", "Korba", "Nabeul", "Menzel Temime", "Grombalia", "Kélibia", "Soliman", "Dar Chaâbane El Fehri", "El Haouaria", "Béni Khiar", "Menzel Bouzelfa", "Bou Argoub", "El Mida", "Takelsa", "Hammam Ghezèze"],
  "Sfax": ["Sfax Ville", "Sfax Ouest", "Sfax Sud", "Sakiet Eddaïer", "Sakiet Ezzit", "Bir Ali Ben Khalifa", "Thyna", "Jebiniana", "El Hencha", "Agareb", "Menzel Chaker", "Mahrès", "Skhira", "El Amra", "Graïba", "Kerkennah"],
  "Sidi Bouzid": ["Sidi Bouzid Ouest", "Sidi Bouzid Est", "Regueb", "Mezzouna", "Meknassy", "Ouled Haffouz", "Souk Jedid", "Cebbala Ouled Asker", "Menzel Bouzaiane", "Sidi Ali Ben Aoun", "Bir El Hafey", "Jilma"],
  "Siliana": ["Makthar", "Rouhia", "Siliana Sud", "Siliana Nord", "El Krib", "Bou Arada", "Gaâfour", "Kesra", "Sidi Bou Pais", "Bargou", "El Aroussa"],
  "Sousse": ["M'saken", "Sousse Riadh", "Sousse Jawhara", "Kalâa Kebira", "Sidi Abdelhamid", "Enfida", "Hammam Sousse", "Sousse Médina", "Kalâa Seghira", "Akouda", "Bouficha", "Sidi Bou Ali", "Kondar", "Sidi El Hani", "Hergla"],
  "Tataouine": ["Tataouine Nord", "Tataouine Sud", "Ghomrassen", "Smâr", "Remada", "Bir Lahmar", "Dehiba"],
  "Tozeur": ["Tozeur", "Degache", "Nefta", "Tameghza", "Hazoua"],
  "Tunis": ["Hraïria", "El Kabaria", "Sidi Hassine", "La Marsa", "Le Bardo", "El Omrane supérieur", "Le Kram", "El Menzah", "El Omrane", "Ezzouhour", "Bab El Bhar", "Cité El Khadra", "Séjoumi", "El Ouardia", "Bab Souika", "Sidi El Béchir", "La Goulette", "Médina", "Djebel Jelloud", "Ettahrir", "Carthage"],
  "Zaghouan": ["El Fahs", "Zaghouan", "Nadhour", "Bir Mcherga", "Zriba", "Saouaf"]
};
